name = "QuantumRecurrencePlots"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComplexRegions = "c64915e2-6c82-11e9-38e9-1f159a780463"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
DomainColoring = "c24f3079-adb7-4533-8329-9f66732e5e85"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
GridapMakie = "41f30b06-6382-4b60-a5f7-79d86b35bf5d"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
NonlinearSolveHomotopyContinuation = "2ac3b008-d579-4536-8c91-a1a5998c2f8b"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ReLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DrWatson = "2.18.0"
julia = "1.11.3"
